# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")
    build_app(workspace: "QuickTutor.xcworkspace", scheme: "QuickTutor")    
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Push a new build to AppStore Connect"
  lane :release do
    get_push_certificate
    build_app(scheme: "QuickTutor")
    upload_to_app_store
    upload_symbols_to_crashlytics(gsp_path: "QuickTutor/New Group/GoogleService-Info.plist")
  end

end
